// commands/fun/wouldyourather.js
const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { getAIResponse } = require('../../utils/ai');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('wouldyourather')
    .setDescription('Get a random Would You Rather question'),

  async execute(interaction) {
    await interaction.deferReply();

    const prompt = "Generate a funny, creative 'Would You Rather' question with two options. Keep it light-hearted and weird.";

    try {
      const question = await getAIResponse(new Map(), 'wyr-session', prompt);

      const embed = new EmbedBuilder()
        .setColor(0xe67e22)
        .setTitle('🤔 Would You Rather...')
        .setDescription(question)
        .addFields({ name: 'Reply with your choice!', value: 'A or B?' })
        .setFooter({ text: 'Generated by Dungeon AI' })
        .setTimestamp();

      await interaction.editReply({ embeds: [embed] });
    } catch (err) {
      await interaction.editReply({ content: 'The AI is too indecisive right now...', ephemeral: true });
    }
  },
};